# Generated by Django 5.0.1 on 2024-01-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='arr1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='arr2',
        ),
        migrations.AddField(
            model_name='match',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
