# Generated by Django 5.0.1 on 2024-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_match_arr1_remove_match_arr2_match_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='data',
            field=models.TextField(),
        ),
    ]
