# Generated by Django 5.0.1 on 2024-01-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_match_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
