# Generated by Django 5.0.1 on 2024-01-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_no', models.DecimalField(decimal_places=0, max_digits=2)),
                ('base_txt', models.TextField()),
                ('learn_txt', models.TextField()),
                ('from_lang', models.TextField()),
                ('to_lang', models.TextField()),
            ],
        ),
    ]
