# Generated by Django 5.0.1 on 2024-01-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_speech'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('level', models.DecimalField(decimal_places=0, max_digits=1)),
                ('lesson', models.DecimalField(decimal_places=0, max_digits=2)),
                ('total_lessons', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
