# Generated by Django 5.0.1 on 2024-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprogressdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('lesson_no', models.DecimalField(decimal_places=0, max_digits=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
