# Generated by Django 5.0.1 on 2024-01-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_arrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('stage_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stage_name', models.TextField()),
                ('total_lessons', models.DecimalField(decimal_places=0, max_digits=2)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
