# Generated by Django 5.0.1 on 2024-01-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
