# Generated by Django 5.0.1 on 2024-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_levels_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_data',
            name='level',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
