# Generated by Django 5.0.1 on 2024-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_arrange_level_match_level_mcq_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogressdata',
            name='gender',
            field=models.CharField(default='male', max_length=6),
            preserve_default=False,
        ),
    ]
