# Generated by Django 5.0.1 on 2024-02-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userprogressdata_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Stages',
        ),
    ]
