# Generated by Django 5.0.1 on 2024-02-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_levels_stages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='total_lessons',
            new_name='total_levels',
        ),
    ]
