# Generated by Django 5.0.1 on 2024-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_total_lessons_stages_total_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('stage_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stage_name', models.TextField()),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('total_lessons', models.DecimalField(decimal_places=0, max_digits=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
