# Generated by Django 5.0.1 on 2024-02-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='code',
            field=models.CharField(default='HIN_ENG', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='stage_name',
            field=models.TextField(default='Beginners'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
