# Generated by Django 5.0.1 on 2024-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_lessons_code_lessons_stage_name_lessons_stage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogressdata',
            name='stage',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogressdata',
            name='level',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
