# Generated by Django 5.0.1 on 2024-02-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_arrange_code_match_code_mcq_code_mcq_data_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_data',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_pic_data',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='stage_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
