# Generated by Django 5.0.1 on 2024-02-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_arrange_stage_number_match_stage_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogressdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprogressdata',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
