# Generated by Django 5.0.1 on 2024-02-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_userprogressdata_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='total_lessons',
        ),
    ]
