# Generated by Django 5.0.1 on 2024-02-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='course',
            field=models.CharField(max_length=15),
        ),
    ]
