# Generated by Django 5.0.1 on 2024-02-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_userdata_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=15)),
                ('stage', models.DecimalField(decimal_places=0, max_digits=1)),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('lesson', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
