# Generated by Django 5.0.1 on 2024-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_userprogressdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange',
            name='from_lang',
            field=models.TextField(default='hi-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrange',
            name='to_lang',
            field=models.TextField(default='en-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='from_lang',
            field=models.TextField(default='hi-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='to_lang',
            field=models.TextField(default='en-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='from_lang',
            field=models.TextField(default='hi-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='to_lang',
            field=models.TextField(default='en-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_data',
            name='from_lang',
            field=models.TextField(default='hi-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_data',
            name='to_lang',
            field=models.TextField(default='en-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_pic_data',
            name='from_lang',
            field=models.TextField(default='hi-IN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_pic_data',
            name='to_lang',
            field=models.TextField(default='en-IN'),
            preserve_default=False,
        ),
    ]
