# Generated by Django 5.0.1 on 2024-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_userdata_lesson_remove_userdata_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('stage_number', models.DecimalField(decimal_places=0, max_digits=2)),
                ('stage_name', models.TextField()),
                ('level', models.DecimalField(decimal_places=0, max_digits=2)),
                ('lesson_no', models.DecimalField(decimal_places=0, max_digits=2)),
                ('question_type', models.CharField(max_length=150)),
                ('ai_prompt', models.TextField()),
            ],
        ),
    ]
