# Generated by Django 5.0.1 on 2024-02-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_questiondata_total_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='total_questions',
        ),
    ]
