# Generated by Django 4.0.6 on 2024-03-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_user_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='course',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='userprogressdata',
            old_name='course',
            new_name='code',
        ),
    ]
