# Generated by Django 4.0.6 on 2024-03-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_course_userdata_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='code',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='userprogressdata',
            old_name='code',
            new_name='course',
        ),
    ]
