# Generated by Django 5.0.1 on 2024-03-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_code_userdata_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institute_code',
            field=models.CharField(default='SELF', max_length=15),
        ),
        migrations.AddField(
            model_name='userdata',
            name='institute_code',
            field=models.CharField(default='SELF', max_length=15),
        ),
    ]
