# Generated by Django 5.0.1 on 2024-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_course_institute_code_userdata_institute_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institute_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('referal_code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('total_students', models.DecimalField(decimal_places=0, max_digits=8)),
                ('max_students', models.DecimalField(decimal_places=0, max_digits=8)),
                ('no_of_courses', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
    ]
