# Generated by Django 5.0.1 on 2024-03-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_institution_referal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution_Course',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('institute_code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('no_of_mock_tests', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
