# Generated by Django 5.0.1 on 2024-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_institution_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Course_Details',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('institute_code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
