# Generated by Django 5.0.1 on 2024-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_all_course_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='no_of_courses',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='institution',
            name='total_students',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
