# Generated by Django 5.0.1 on 2024-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_institution_no_of_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_course',
            name='no_of_mock_tests',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
