# Generated by Django 5.0.1 on 2024-03-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_userprogressdata_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_pic_data',
            name='question',
            field=models.TextField(default='Choose the correct option'),
        ),
    ]
