# Generated by Django 5.0.1 on 2024-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_mcq_pic_data_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('institute_code', models.CharField(max_length=15)),
                ('Mock_Test_Number', models.DecimalField(decimal_places=0, default=-1, max_digits=10)),
                ('Total_Marks', models.DecimalField(decimal_places=0, max_digits=2)),
                ('Total_Time', models.DecimalField(decimal_places=0, max_digits=4)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
