# Generated by Django 5.0.1 on 2024-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_mock_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_test',
            name='Total_Marks',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
