# Generated by Django 5.0.1 on 2024-03-27 15:48

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_mock_test_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_Test_MCQ_Type_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_code', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('Mock_Test_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.TextField()),
                ('option1_link', models.FileField(upload_to=home.models.unique_file_path)),
                ('option2_link', models.FileField(upload_to=home.models.unique_file_path)),
                ('option3_link', models.FileField(upload_to=home.models.unique_file_path)),
                ('option4_link', models.FileField(upload_to=home.models.unique_file_path)),
                ('from_lang', models.TextField()),
                ('to_lang', models.TextField()),
            ],
        ),
    ]
