# Generated by Django 5.0.1 on 2024-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_mock_test_mcq_type_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mock_test_mcq_type_1',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='mock_test_mcq_type_1',
            name='to_lang',
        ),
    ]
