# Generated by Django 5.0.1 on 2024-03-27 16:19

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_mock_test_mcq_type_1_from_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_Test_MCQ_Pic_Data_Type_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_code', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('Mock_Test_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('question', models.TextField(default='Choose the correct option')),
                ('img_link', models.FileField(upload_to=home.models.unique_file_path)),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mock_Test_MCQ_Type_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_code', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('Mock_Test_Number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
