# Generated by Django 5.0.1 on 2024-03-27 16:51

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_mcq_data_option1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_pic_data',
            name='img_link',
            field=models.FileField(upload_to=home.models.unique_file_path),
        ),
    ]
