# Generated by Django 5.0.1 on 2024-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_mcq_pic_data_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrange',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='match',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mcq',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mcq_data',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mcq_pic_data',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mock_test_mcq_pic_data_type_2',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mock_test_mcq_type_1',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='mock_test_mcq_type_3',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
        migrations.AddField(
            model_name='speech',
            name='marks',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
    ]
