# Generated by Django 5.0.1 on 2024-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_arrange_marks_match_marks_mcq_marks_mcq_data_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock_test',
            name='number_of_attempts',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=4),
        ),
    ]
