# Generated by Django 5.0.1 on 2024-04-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_loggedinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_data',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='mcq_data',
            name='to_lang',
        ),
    ]
