# Generated by Django 5.0.1 on 2024-04-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_remove_mcq_data_from_lang_remove_mcq_data_to_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrange',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='arrange',
            name='to_lang',
        ),
        migrations.RemoveField(
            model_name='match',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='match',
            name='to_lang',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='to_lang',
        ),
        migrations.RemoveField(
            model_name='mcq_pic_data',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='mcq_pic_data',
            name='to_lang',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='to_lang',
        ),
    ]
