# Generated by Django 5.0.1 on 2024-04-13 09:22

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_written_mock_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('institute_code', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=200)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=home.models.pdf_unique_file_path)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('institute_code', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionData',
        ),
    ]
