# Generated by Django 5.0.1 on 2024-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_course_material_course_topic_delete_questiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='total_lessons',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='stages',
            name='total_levels',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
