# Generated by Django 5.0.1 on 2024-04-13 11:52

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_levels_total_lessons_alter_stages_total_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=home.models.pdf_unique_file_path),
        ),
    ]
