# Generated by Django 5.0.1 on 2024-04-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_institution_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
    ]
