# Generated by Django 5.0.1 on 2024-04-13 12:02

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_remove_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=home.models.institute_images_unique_file_path),
        ),
    ]
