# Generated by Django 5.0.1 on 2024-04-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_written_mock_test_results_question_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Institution_Course',
        ),
    ]
